extends Node

signal enemy_killed(enemy_id: String, gold_reward: int, sacred_fire_reward: int)
signal tower_built(tower_id: String)
signal tower_upgraded(tower_id: String, new_level: int)
signal tower_sold(tower_id: String, refund: int)
signal tower_hijack_started(placement_id: String)
signal tower_hijack_recovered(placement_id: String)
signal tower_resonance_linked(combo_id: String)
signal region_state_changed(region_id: String, state: GameEnums.RegionLightState)
signal wave_started(wave_index: int)
signal wave_phase_started(wave_index: int, phase: String)
signal wave_completed(wave_index: int)
signal battle_started(level_id: String)
signal battle_completed(victory: bool, level_id: String)
signal fate_card_selected(card_id: String)
signal cleanse_used(region_id: String)
signal hero_moved
signal hero_skill_used(skill_id: String)
signal hero_melee_used(action_id: String)
signal hero_dodged
signal hero_damaged(amount: float)
signal hero_melee_kill(enemy_id: String)
signal tower_damage_dealt(tower_id: String, amount: float, enemy_id: String)
signal enemy_stunned(source: String, enemy_id: String)
signal naft_slick_ignited(route_id: String)
